bklynhlth/openwillis

openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py
Adding parameter for speaker filtering in transcripts
Methods doc: https://docs.google.com/document/d/1FwIC7CYCMqf_rXrvd2_TKYQs6Ei3K3jrq6gK9Nkkv_Y/edit
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204810900671768
=> Speech characteristics v1.1

openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py
Remove mattr calculation for word-summary
Ticket: https://app.asana.com/0/0/1205000408302968/f
=> mattr bug calculcation

openwillis/measures/text/util/characteristics_util.py
Fix RuntimeWarning when dividing by 0
Ticket: https://app.asana.com/0/0/1205000408302964/f
=> Conditionals for not dividing by 0

openwillis/__init__.py, openwillis/measures/api.py, openwillis/measures/audio/__init__.py, openwillis/measures/audio/speech_separation_cloud.py, setup.py
=> speaker separation cloud

openwillis/measures/video/eye_blink.py
Remove docstring about raising error from previous version
=> removed deprecated docstring in eye blink

openwillis/measures/audio/util/transcribe_util.py
- ThrottlingException handling
=> GetTranscriptionJob ThrottlingException handling

openwillis/measures/audio/util/transcribe_util.py
=> sleep time update

openwillis/measures/audio/util/transcribe_util.py
- logs to check throttling exception
=> adding logs

openwillis/measures/audio/util/transcribe_util.py
- sleep threshold for handling throttling exception.
=> sleep threshold

openwillis/measures/video/face_landmark.py, openwillis/measures/video/facial_emotion.py, setup.py
- remove std from facial features
=> facial update

openwillis/measures/video/eye_blink.py, requirements.txt
* add scipy latest version (eye blink function is dependent on scipy)
* return empty dataframe for eyeblink function in case of any exception
* add relevant error message in exception handling
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205466037161966
=> Eyeblink issues

openwillis/measures/audio/speech_transcribe.py, openwillis/measures/audio/util/whisperx_util.py
- Update in whisperx CPU configuration
=> wshiperx cpu update

openwillis/measures/text/speech_attribute.py
Move language string processing inside try logic
=> Check for empty language string

openwillis/measures/audio/speech_separation.py, openwillis/measures/audio/speech_transcribe.py, openwillis/measures/audio/util/separation_util.py, openwillis/measures/audio/util/transcribe_util.py, openwillis/measures/audio/util/whisperx_util.py, openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py, requirements.txt, setup.py
Whisperx support in following methods
- speech transcription
- speaker separation
- speech characteristics
=> 1.5.x to main

openwillis/measures/audio/util/separation_util.py, openwillis/measures/audio/util/transcribe_util.py
- Fix speaker separation in case of missing speaker labels from whisperx
=> speaker separation fix

openwillis/measures/text/speech_attribute.py
Remove segments without speaker from transcription
=> Speech chars - bug when no speaker in transcript

openwillis/measures/audio/speech_transcribe.py, openwillis/measures/audio/util/transcribe_util.py, openwillis/measures/audio/util/whisperx_util.py, openwillis/measures/text/util/characteristics_util.py
- Handling exception in speech characteristic pause filtering
=> speech characteristic fix

openwillis/measures/audio/util/separation_util.py, openwillis/measures/text/speech_attribute.py
- handling unexpected behavior in speech characteristic and speaker separation
=> handling unexpected beahvior

openwillis/__init__.py, openwillis/measures/api.py, openwillis/measures/audio/__init__.py, openwillis/measures/audio/speech_separation_labels.py, openwillis/measures/audio/speech_separation_nlabels.py, openwillis/measures/audio/util/separation_util.py, openwillis/measures/commons/common.py
Speech transcription support:
- [Speaker Separation without Labels ](https://docs.google.com/document/d/1z5wdIK0xg22zo_JOqnfbpRsquLHNVfFPJBRdQDBkxdE/edit)
- [Speaker Separation with Labels  ](https://docs.google.com/document/d/1mA6suztiKlK9obxKl8TRO80yZmaoTbTY9lFFfr3z2FY/edit)
=> speaker separation update

openwillis/measures/audio/speech_transcribe_whisper.py, openwillis/measures/audio/util/transcribe_util.py
=> Multiple speaker labeling

requirements.txt
Add forest requirement for GPS processing
=> Add library requirement

openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py
Changes:
* Fix word level logic issue around pauses when filtering turns
* Fix summary level measures when filtering turns
Methods Doc: https://docs.google.com/document/d/1ymyU4cX6gITnIBd8IsqL-5H9AU9HqATYgV8Wont3f04/edit
=> Speech Characteristics 2.3

setup.py
- downgrade vosk to 0.3.44 (support for mac machines)
- speech characteristics 2.3
- upgrade transformer version
- GPS V1.0
=> openwillis release v2.0

requirements.txt, setup.py
=> openwillis release v2.0.1

openwillis/measures/audio/speech_transcribe_cloud.py, setup.py
Do not run speaker identification if only single speaker detected by AWS
=> Transcribe AWS single speaker bug

openwillis/measures/audio/speech_transcribe_whisper.py, openwillis/measures/audio/util/whisperx_util.py, setup.py
Update speech transcription function with WhisperX to add parameters for `compute_type` and `batch_size` in WhisperX.
=> WhisperX transcription add parameters

openwillis/measures/text/util/diarization_utils.py
Client inside `process_chunk` for parallel processing, because otherwise argument fails to pickle
=> Bug in Parallel Processing

openwillis/measures/audio/acoustic.py
Import disvoice util only if advanced measures are needed in vocal acoustic
=> Advanced vocal acoustics import

openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py
Add `option` parameter to define which measures to calculate
Methods Doc: https://docs.google.com/document/d/1iFj52oQAo8sHdLAtcpu7K6IrAZass5yZ4iCziEhDkks/edit
=> Speech chars v3.1

openwillis/measures/text/util/diarization_utils.py
Fix warning about tokenizer when making parallel requests
Solution: https://stackoverflow.com/questions/62691279/how-to-disable-tokenizers-parallelism-true-false-warning
=> Tokenizer parallelism warning

openwillis/__init__.py, openwillis/measures/api.py, openwillis/measures/text/__init__.py, openwillis/measures/text/willisdiarize_aws.py
Renaming function name for diarization correction with sagemaker endpoint
=> Rename LLM Diarization funtion to WillisDiarize AWS

openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py
Change option from `advanced` to `coherence`
=> Speech Chars 3.1 option parameter

requirements.txt
Pyannote version: 3.0.0 → 3.1.1
=> Update version of pyannote

openwillis/__init__.py, openwillis/measures/api.py, openwillis/measures/text/__init__.py, openwillis/measures/text/util/diarization_hf_utils.py, openwillis/measures/text/util/diarization_utils.py, openwillis/measures/text/util/huggingface_utils.py, openwillis/measures/text/willisdiarize.py
Diarization correction with HuggingFace models
Methods Doc: https://docs.google.com/document/d/1VjmHxTDxS6s1DJ-uGyUjQxavqmuiGkwULJjbPG5IeRI/edit#heading=h.ms9pl2pmmwrz
=> WillisDiarize v1.0

openwillis/measures/audio/speech_transcribe_whisper.py, openwillis/measures/text/willisdiarize.py
Methods Doc: https://docs.google.com/document/d/1LrkhIqwSfPM_S7sBhYXMT8pDgN-imuS6V8q4cFNZdQc/edit
=> Speech Transcription Whisper v1.2

MANIFEST.in, openwillis/measures/audio/acoustic.py
Methods Doc: https://docs.google.com/document/d/1RnIxMqTEHf1JwyVtnLB7u8KIND43Mzeh7vTOPW5Ii18/edit
=> Vocal acoustics v2.1

openwillis/measures/audio/speech_transcribe_cloud.py, openwillis/measures/audio/util/transcribe_util.py, openwillis/measures/text/willisdiarize_aws.py
Methods Doc: https://docs.google.com/document/d/1RoH7zpwl3CBNnrrvr9qHDSwG1hmzw8hVEJ_SEVE5ouU/edit
=> Speech Transcription AWS v1.2

.github/workflows/python-publish.yml
Whenever a PR gets merged into the main branch, it should push it to PyPI automatically using Github actions.
=> Automatic PyPI update

openwillis/measures/audio/acoustic.py
* when no silence return entire frame count
* when 1 silence no need for specific check
* ensure final speech has minimum duration required
=> Bug in voiced segments calculation

openwillis/measures/audio/speech_transcribe_cloud.py, openwillis/measures/text/util/diarization_utils.py, openwillis/measures/text/util/huggingface_utils.py
* Fix `willisdiarize_status` being referenced before assignment
* Use exponential retry with parallel processing logic
=> AWS transcription bugs

openwillis/measures/audio/speech_transcribe_cloud.py
Bug return statement when more or less than 2 speakers detected
=> Speech Transcription cloud should always return willisdiarize status

openwillis/measures/text/util/huggingface_utils.py
Ensure CUDA available and place model + inputs to GPU
=> WillisDiarize GPU

openwillis/measures/text/util/characteristics_util.py, setup.py
Remove words which don't have timepoints from ASR
=> Speech Characteristics with WhisperX Bug

openwillis/measures/video/__init__.py, openwillis/measures/video/util/__init__.py, setup.py
Issue with video/util not being installed in Windows machines. Add `__init__` module in util directory.
=> Windows bug in import openwillis

openwillis/__init__.py, openwillis/measures/api.py, openwillis/measures/audio/__init__.py, openwillis/measures/audio/speech_preprocess.py, openwillis/measures/commons/common.py
Function to standardize audio files and remove background noise.
Methods Doc: https://docs.google.com/document/d/1nYmqTd_tpwDIOWDpU8jfgyLteE9mQcDv54hhV8aJJ_A/edit
=> Audio preprocess v1.0

openwillis/measures/audio/speech_phonation.py, openwillis/measures/audio/util/phonation_util.py
* Function name typo: Should be `phonation_acoustics` not `phonations_acoustics`
* Setting with copy warnings
=> Phonation Acoustics minor changes

openwillis/measures/audio/speech_phonation.py, openwillis/measures/audio/util/phonation_util.py
Fix bug/error message that occurs when no suitable phonations are detected.
=> Phonation Acoustics: no phonations detected bug

openwillis/measures/audio/acoustic.py, openwillis/measures/audio/speech_preprocess.py, openwillis/measures/audio/speech_separation_labels.py, openwillis/measures/audio/speech_separation_nlabels.py, openwillis/measures/audio/speech_transcribe_vosk.py, openwillis/measures/audio/util/separation_util.py, openwillis/measures/audio/util/transcribe_util.py, openwillis/measures/audio/util/whisperx_util.py, openwillis/measures/commons/common.py, openwillis/measures/gps/geolocation_processing.py, openwillis/measures/text/speech_attribute.py, openwillis/measures/text/util/characteristics_util.py, openwillis/measures/text/util/speech/coherence.py, openwillis/measures/text/util/speech/lexical.py, openwillis/measures/text/util/speech/pause.py, openwillis/measures/text/willisdiarize.py, openwillis/measures/text/willisdiarize_aws.py, openwillis/measures/video/eye_blink.py, openwillis/measures/video/face_landmark.py, openwillis/measures/video/facial_emotion.py, openwillis/measures/video/preprocess_video.py
Change `logger.error` to `.info`
=> Change logger

openwillis/measures/audio/speech_phonation.py
Added more logs in phonation acoustics
=> Phonation logs

.github/workflows/python-publish.yml
Upload package distribution from correct directory
=> Update publish workflow

.github/workflows/python-publish.yml, openwillis-face/setup.py, openwillis-gps/setup.py, openwillis-speech/setup.py, openwillis-transcribe/setup.py, openwillis-voice/setup.py, openwillis/setup.py
* Correct package names in setup
* Publish to pypi workflow: sequential instead of parallel
=> Sequential publish workflow + namings

openwillis-face/setup.py, openwillis-gps/setup.py, openwillis-speech/setup.py, openwillis-transcribe/requirements.txt, openwillis-transcribe/setup.py, openwillis-transcribe/src/openwillis/transcribe/util/whisperx_util.py, openwillis-voice/setup.py, openwillis/setup.py
WhisperX issues have been resolved by the maintainers, so there is no longer need to edit their package on our side.
=> Speech transcription with WhisperX: Dependency update

openwillis-face/setup.py, openwillis-gps/setup.py, openwillis-speech/setup.py, openwillis-transcribe/setup.py, openwillis-voice/setup.py, openwillis-voice/src/openwillis/voice/util/acoustic_util.py, openwillis/setup.py
For f0 and f1-4, a value of 0 is assigned in Praat at frames where calculation is committed or outside frequency range, which affects the summary calculation unless filtered out.
=> Vocal acoustics summary

openwillis-face/setup.py, openwillis-gps/setup.py, openwillis-speech/setup.py, openwillis-transcribe/setup.py, openwillis-voice/setup.py, openwillis-voice/src/openwillis/voice/util/acoustic_util.py, openwillis/setup.py
Bug for selecting column in series
=> Vocal Acoustics Summary Bug
